const actions = {
    USER_SET: 'USER_SET',
    TOKEN: 'TOKEN',
    AUTH_ERROR: 'AUTH_ERROR',

    SET_PREF: 'SET_PREF',
    SET_PROFILE: 'SET_PROFILE',
    SET_PREFERENCE: 'SET_PREFERENCE',
    SET_PROVIDER_SEARCH: 'SET_PROVIDER_SEARCH',
    SET_PROVIDER_DETAIL: 'SET_PROVIDER_DETAIL',
    SET_STYLES: 'SET_STYLES',
    SET_PREVIOUS_APPOINTMENT: 'SET_PREVIOUS_APPOINTMENT',
    SET_UPCOMING_APPOINTMENT: 'SET_UPCOMING_APPOINTMENT',

    ALREADY_FETCH_PROVIDER: 'ALREADY_FETCH_PROVIDER',

    GET_STYLES_PENDING: 'GET_STYLES_PENDING',
    GET_STYLES_FULFILLED: 'GET_STYLES_FULFILLED',
    GET_STYLES_REJECTED: 'GET_STYLES_REJECTED',

    GET_PREFERENCE_PENDING: 'GET_PREFERENCE',
    GET_PREFERENCE_FULFILLED: 'GET_PREFERENCE_FULFILLED',
    GET_PREFERENCE_REJECTED: 'GET_PREFERENCE_REJECTED',

    GET_PROFILE_PENDING: 'GET_PROFILE_PENDING',
    GET_PROFILE_FULFILLED: 'GET_PROFILE_FULFILLED',
    GET_PROFILE_REJECTED: 'GET_PROFILE_REJECTED',

    GET_PREVIOUS_APPOINTMENT_PENDING: 'GET_PREVIOUS_APPOINTMENT_PENDING',
    GET_PREVIOUS_APPOINTMENT_FULFILLED: 'GET_PREVIOUS_APPOINTMENT_FULFILLED',
    GET_PREVIOUS_APPOINTMENT_REJECTED: 'GET_PREVIOUS_APPOINTMENT_REJECTED',

    REPLACE_APPOINTMENT: 'REPLACE_APPOINTMENT',

    GET_UPCOMING_APPOINTMENT_PENDING: 'GET_UPCOMING_APPOINTMENT_PENDING',
    GET_UPCOMING_APPOINTMENT_FULFILLED: 'GET_UPCOMING_APPOINTMENT_FULFILLED',
    GET_UPCOMING_APPOINTMENT_REJECTED: 'GET_UPCOMING_APPOINTMENT_REJECTED',

    GET_PROVIDER_DETAIL_PENDING: 'GET_PROVIDER_DETAIL_PENDING',
    GET_PROVIDER_DETAIL_FULFILLED: 'GET_PROVIDER_DETAIL_FULFILLED',
    GET_PROVIDER_DETAIL_REJECTED: 'GET_PROVIDER_DETAIL_REJECTED',

    GET_PROVIDER_PENDING: 'GET_PROVIDER_PENDING',
    GET_PROVIDER_FULFILLED: 'GET_PROVIDER_FULFILLED',
    GET_PROCIDER_REFJECTED: 'GET_PROCIDER_REFJECTED',
}

export {
    actions
}