const actions = {
    USER_SET: 'USER_SET',
    TOKEN: 'TOKEN',
    AUTH_ERROR: 'AUTH_ERROR',
    SET_PREF: 'SET_PREF',
    SET_PROFILE: 'SET_PROFILE',
    GET_PROFILE: 'GET_PROFILE',
    SET_PREFERENCE: 'SET_PREFERENCE',
    GET_PREFERENCE: 'GET_PREFERENCE',
}

export {
    actions
}