const actions = {
    USER_SET: 'USER_SET',
    TOKEN: 'TOKEN',
    AUTH_ERROR: 'AUTH_ERROR',
    SET_PREF: 'SET_PREF',
    SET_PROFILE: 'SET_PROFILE',
    SET_PREFERENCE: 'SET_PREFERENCE',
    SET_PROVIDER_SEARCH: 'SET_PROVIDER_SEARCH',
    GET_PROVIDER_PENDING: 'GET_PROVIDER_PENDING',
    GET_PROVIDER_FULFILLED: 'GET_PROVIDER_FULFILLED',
    GET_PROCIDER_REFJECTED: 'GET_PROCIDER_REFJECTED'
}

export {
    actions
}