export default {
    inputStyleLeft: {
        color: '#000',
        backgroundColor:  '#ffffff',
        color: '#000',
        backgroundColor:  '#fff',
        fontSize: 18,
        lineHeight: 3,
        flex: 2,
        width: 166,
        height: 38,
        alignItems: 'flex-start',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 2,
    },
    inputStyleOs: {
      color: '#000',
      backgroundColor:  '#ffffff',
      paddingRight: 5,
      paddingLeft: 5,
      paddingBottom: 20,
      fontSize: 18,
      lineHeight: 3,
      flex: 2,
        color: '#000',
        backgroundColor:  '#fff',
        width: 166,
        height: 38,
        alignItems: 'flex-start',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 2,
    },
    labelStyle: {
      fontSize: 16,
      flex: 1,
      paddingBottom: 10
    },
    containerStyleLeft: {
      display: 'flex',
      flexDirection: 'column',
      flexBasis: 90,
      justifyContent: 'center',
      alignItems: 'center',
      flex: 1,
      margin: 5,
      backgroundColor:  '#ffffff',
      alignItems: 'flex-start'
    },
    error: {
      marginTop: 10,
      position: "absolute",
      bottom: 0,
      color: "red",
      fontSize: 10,
      textAlign: 'center',
      backgroundColor:  '#ffffff'
    },
    inputStyleRight: {
      color: '#000',
        backgroundColor:  '#ffffff',
        paddingRight: 5,
        paddingLeft: 5,
        paddingBottom: 20,
        color: '#000',
        backgroundColor:  '#fff',
        fontSize: 18,
        lineHeight: 3,
        flex: 2,
        width: 166,
        height: 38,
        alignItems: 'flex-start',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 2,
    },
    inputStyleOsRight: {
      color: '#000',
      backgroundColor:  '#ffffff',
      paddingRight: 5,
      paddingLeft: 5,
      paddingBottom: 20,
      fontSize: 18,
      lineHeight: 3,
      flex: 2,
      color: '#000',
      backgroundColor:  '#fff',
      width: 166,
      height: 38,
      alignItems: 'flex-start',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 2,
    },
    labelStyleRight: {
      fontSize: 16,
      flex: 1,
      paddingBottom: 10
    },
    containerStyleRight: {
      display: 'flex',
      flexDirection: 'column',
      flexBasis: 90,
      justifyContent: 'center',
      alignItems: 'center',
      flex: 1,
      margin: 5,
      backgroundColor:  '#ffffff',
      alignItems: 'flex-start'
    },
    errorAndroid: {
      marginTop: 10,
      position: "absolute",
      bottom: 0,
      color: "red",
      fontSize: 10,
      textAlign: 'center',
      justifyContent: 'center',
      elevation: 1,
    },
    inputStyleAndroid: {
      color: '#000',
      backgroundColor:  '#ffffff',
      paddingRight: 5,
      paddingLeft: 5,
      paddingBottom: 20,
      color: '#000',
      backgroundColor:  '#ffffff',
      fontSize: 18,
      lineHeight: 3,
      flex: 2,
      shadowOpacity: 1,
      shadowRadius: 5,
      shadowOffset: {
          height: 10,
          width: 5,
      },
      elevation: 1,
    }
  };