export default {
    inputStyle: {
        color: '#000',
         backgroundColor:  '#ffffff',
         paddingRight: 5,
         paddingLeft: 5,
         paddingBottom: 20,
         color: '#000',
         backgroundColor:  '#fff',
         fontSize: 18,
         lineHeight: 3,
         flex: 2,
         width: 166,
         height: 38,
         alignItems: 'flex-start',
         shadowColor: '#000',
         shadowOffset: { width: 0, height: 2 },
         shadowOpacity: 0.3,
         shadowRadius: 2,
         //marginTop: 100,
      },
      inputStyleOs: {
        color: '#000',
        backgroundColor:  '#ffffff',
        paddingRight: 5,
        paddingLeft: 5,
        paddingBottom: 20,
        fontSize: 18,
        lineHeight: 3,
        flex: 2,
         color: '#000',
         backgroundColor:  '#fff',
         width: 166,
         height: 38,
         alignItems: 'flex-start',
         shadowColor: '#000',
         shadowOffset: { width: 0, height: 2 },
         shadowOpacity: 0.3,
         shadowRadius: 2,
      },
      labelStyle: {
        fontSize: 16,
        flex: 1,
        paddingBottom: 10
      },
      containerStyle: {
        display: 'flex',
        flexDirection: 'column',
        flexBasis: 90,
        justifyContent: 'center',
        alignItems: 'center',
        flex: 1,
        margin: 10,
        backgroundColor:  '#ffffff',
        alignItems: 'flex-start'
      },
      error: {
        marginTop: 10,
        position: "absolute",
        bottom: 0,
        color: "red",
        fontSize: 10,
        textAlign: 'center',
        backgroundColor:  '#ffffff'
      }
  };