export default {
    textStyle: {
      alignSelf: 'center',
      color: '#fff',
      fontSize: 16,
      fontWeight: '600',
      paddingTop: 5,
      paddingBottom: 5,        
      justifyContent: 'center',
      alignItems: 'center',
    },
    buttonStyle: {
      flex: 1,
      backgroundColor:'#4FA6FD' ,
      borderRadius: 5,
      borderWidth: 1,
      borderColor: '#fff',
      marginTop: 100,
      marginLeft: 10,
      marginRight: 10,
      width: 250, 
      justifyContent: 'center',
      alignItems: 'center',
      width: 293,
      height: 54,
    },
    buttonStylePurple: {
      flex: 1,
      backgroundColor:'#724FFD' ,
      borderRadius: 5,
      borderWidth: 1,
      borderColor: '#fff',
      marginLeft: 10,
      marginRight: 10,
      width: 250, 
      justifyContent: 'center',
      alignItems: 'center',
      width: 293,
      height: 54,
    },
    smallButtonStylePurple: {
      flex: 1,
      backgroundColor:'#fff' ,
      borderRadius: 1,
      borderWidth: 1,
      borderColor: '#724FFD',
      marginLeft: 10,
      marginRight: 10,
      justifyContent: 'center',
      alignItems: 'center',
      width: 101,
      height: 40,
      marginTop: 22,
      marginBottom: 20,
    },
    smallButtonStyleFillPurple: {
      flex: 1,
      backgroundColor:'#724FFD' ,
      borderRadius: 1,
      borderWidth: 1,
      borderColor: '#724FFD',
      marginLeft: 10,
      marginRight: 10,
      justifyContent: 'center',
      alignItems: 'center',
      width: 101,
      height: 40,
      marginTop: 22,
      marginBottom: 20,
    },
    whiteFillTextStyle: {
      alignSelf: 'center',
      color: '#724FFD',
      fontSize: 14,
      fontWeight: '600',
      paddingTop: 5,
      paddingBottom: 5,        
      justifyContent: 'center',
      alignItems: 'center',
    }
  };